version: '3'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data_elixir:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "5432:5432"
  
volumes:
  postgres_data_elixir:
